//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СonferenceEntities1 : DbContext
    {
        public СonferenceEntities1()
            : base("name=СonferenceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conference> Conference { get; set; }
        public virtual DbSet<EquipAndPerf> EquipAndPerf { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<PerfAndSpeaker> PerfAndSpeaker { get; set; }
        public virtual DbSet<Performance> Performance { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Speaker> Speaker { get; set; }
    }
}
