//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipAndPerf
    {
        public int idPerf { get; set; }
        public int idEquip { get; set; }
        public int id { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Performance Performance { get; set; }
    }
}
