//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int idEquip { get; set; }
        public string nameEquip { get; set; }
        public Nullable<int> idPerf { get; set; }
    
        public virtual Performance Performance { get; set; }
    }
}
