//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speaker
    {
        public int idSpeaker { get; set; }
        public string degreeSpeaker { get; set; }
        public string academStatus { get; set; }
        public string placeOfWork { get; set; }
        public string positionSpeaker { get; set; }
        public string profBiogSpeaker { get; set; }
        public Nullable<int> idPerf { get; set; }
    
        public virtual Performance Performance { get; set; }
    }
}
