//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speaker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Speaker()
        {
            this.PerfAndSpeakers = new HashSet<PerfAndSpeaker>();
        }
    
        public int idSpeaker { get; set; }
        public string degreeSpeaker { get; set; }
        public string academStatus { get; set; }
        public string placeOfWork { get; set; }
        public string positionSpeaker { get; set; }
        public string profBiogSpeaker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerfAndSpeaker> PerfAndSpeakers { get; set; }
    }
}
